  Learn MarkDown and show all of basic usage in the ShortQuestions/README.md
1.  https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formattin
g-on-github/basic-writing-and-formatting-syntax
2.  practice git using the platform. list the git commands you learned. Git init, git branch, git checkout, git checkout -b, mkdir, git clone, git status, git fetch –all, git branch -r 
1.  https://learngitbranching.js.org/
3.  What is the basic steps to init a git repo in you local ? git init
4.  How to clone a repo from Github ?  git clone URL
5.  How to create a new branch and checkout to that branch ? git checkout -b branchname
6.  How to merge the branch_test to master branch in command ? show me the commands
7.  How to stash your new code before leaving branch branch_learn_stash and pop your stash when you 
checkout back to **branch_learn_stash ? try commands way and intellij way. To stash, type:  git stash
                                                                                              Do the merge, and then pull the stash: git stash pop
                        In Intellij,  select Git | Uncommitted Changes | Stash Changes. Click Create Stash
8.  How do you understand PR is based on Branch?  Pull requests tell others about changes  you've  pushed to a branch in a repository on GitHub.
9.  What is maven role ? what it be used to do ? Maven allows developers to create projects, dependency, and documentation using Project Object Model and plugins. It helps manage all the processes, such as building, documentation, releasing, and distribution in project management
10.  What is the lifecycle of maven? could you tell me the details ? clean->prepare-resource->validate->package->install
Cleans the project and removes all files generated by the previous build.
Compile source code of the project, validate the project structure is correct. This step packages the compiled code in distributable format like JAR or WAR, 
This step installs the packaged code to the local Maven repository.
11.  what is the difference between package and install in maven lifecycle ? package will compile the code and also package it.
install will compile and package, but it will also put the package in local repository.
12.  What is plugins in maven, list some plugins. The JAR files, and dependencies that maven provide. Clean, compiler, deploy, install …
13.  In chuwa1010, MavenProject directory, create a maven Module using Intellij, named it as belows:
1.  groupID: com.chuwa.learn
2.  artifactID: java-core
14.  Do Code Review: Go over the PRs in your repo, tried to leave some useful or useful comments in other  students' PR, please don't merge 
